server-start: true
server-stop: true
block-place: true
block-break: true
join: true
leave: true
chat: true
commands: true
tnt-ignite: true
world-change: true

command-blacklist:
  #- command1
  #- command2